(package "use-ttf"
         "0.1.3"
         "Keep font consistency across different OSs")

(website-url "https://github.com/jcs-elpa/use-ttf")
(keywords "convenience" "customize" "font" "install" "ttf")

(package-file "use-ttf.el")

(source "melpa")

(depends-on "emacs" "24.4")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
